### PR TITLE
Respect 1D features in volume

### PR DESCRIPTION
**Pull request by lrineau**
I wanted to fix something after a [recent discussion on the mailing list](https://groups.google.com/d/msgid/iso2mesh-users/7cbb74fd-f9f4-4885-9a65-0daf55a42acfn%40googlegroups.com).

CGAL functions can mesh a volume that intersects the box of the image. That is [the example "Domains from Segmented 3D Images, with 1D Features", from the manual](https://doc.cgal.org/5.3/Mesh_3/#title36).

This PR updates the code of `mesh_3D_image.cpp` accordingly.

### CODE REVIEW

**Comment by lrineau** [comment]
I have verified this PR with the following code:
```
% create a 2d binary image
[xi,yi]=ndgrid(0:60,0:40);
d2=(xi-30).*(xi-30)+(yi-20).*(yi-20);
img=zeros(size(xi));
img(d2<100)=1;
im3d=repmat(img,1,1,50);

% extract object from binary volume
[no1,el1]=v2m(uint8(im3d),[],struct('radbound',3,'distbound',0.2),8,'cgalmesh');

plotmesh(no1,el1,'y>20')
```
and the results is:
Screenshot_20210920_164230

**Comment by fangq** [comment]
this is terrific! thank you for sharing. I will test it on my side.

**Comment by SYP-code** [comment]
> I wanted to fix something after a [recent discussion on the mailing list](https://groups.google.com/d/msgid/iso2mesh-users/7cbb74fd-f9f4-4885-9a65-0daf55a42acfn%40googlegroups.com).
> 
> CGAL functions can mesh a volume that intersects the box of the image. That is [the example "Domains from Segmented 3D Images, with 1D Features", from the manual](https://doc.cgal.org/5.3/Mesh_3/#title36).
> 
> This PR updates the code of `mesh_3D_image.cpp` accordingly.

Hi lrineau, for the problem that the surface mesh is not smooth, I tried to replace the "mesh_3D_image.cpp" file with the code you recommended, but the mesh doesn't seem to improve, what is the reason for this?

Thanks.
image

**Comment by fangq** [comment]
statically linked cgalmesh executable for Linux

[cgalmesh.mexa64.zip](https://github.com/fangq/iso2mesh/files/8673607/cgalmesh.mexa64.zip)

**Comment by SYP-code** [comment]
Thank you for your reply, Dr. Fang. Is there an alternative to windows?













At 2022-05-12 05:41:15, "Qianqian Fang" ***@***.***> wrote:

statically linked cgalmesh executable for Linux

cgalmesh.mexa64.zip

**Pull request merged**
