### PR TITLE
compatibility with CGAL 6.0

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by fangq** [comment]
@sloriot, thanks for the patch - can you add macros to allow this patched code to be also compiled with older versions of CGAL? I will be happy to test if you add those.

**Comment by sloriot** [comment]
What is the minimal version of CGAL you want to be compatible with?

**Comment by fangq** [comment]
@sloriot, thanks again for the patch - I tested this on Ubuntu 20.04, the cmake command failed with the following error:

```
if test -f cgalmesh/CMakeLists.txt; then cd cgalmesh && cmake . && cd ..; fi
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")  
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0")  
CMake Error at CMakeLists.txt:45 (include):
  include could not find load file:

    CGAL_TBB_support


CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGAL_enable_end_of_configuration_hook.cmake:99 (message):
  =======================================================================

  CGAL performance notice:

  The variable CMAKE_BUILD_TYPE is set to "".  For performance reasons, you
  should set CMAKE_BUILD_TYPE to "Release".

  Set CGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE to TRUE if you want to disable
  this warning.

  =======================================================================
Call Stack (most recent call first):
  CMakeLists.txt:9999 (CGAL_run_at_the_end_of_configuration)
```

it appears that this is related to the newly required [CGAL_TBB_support file](https://github.com/fangq/iso2mesh/pull/79/files#diff-d77f3e592710231b37701718bb48c2e249ca6eb3f197d254d899c1ec5608ac3fR45). would it be possible to add support  to Ubuntu 20.04 (with libcgal-dev 5.0.3)?

**Comment by fangq** [comment]
@sloriot, thanks a lot for polishing this patch.

after updating with your latest commit, I was able to build `cgalmesh` on my Ubuntu 20.04 boxes, but now the build gave the following error when building `cgalsimp2`. I tested the original makefile on 20.04 and it builds cgalsimp2 correctly.

are you able to reproduce this error? 

```
if test -f cgalsimp2/CMakeLists.txt; then cd cgalsimp2 && cmake . && cd ..; fi
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
CMake Error: Generator: execution of make failed. Make command was: /usr/bin/gmake cmTC_94bd2/fast && 
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/users/fangq/space/git/Temp/iso2mesh/tools/cgalsimp2/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake cmTC_94bd2/fast && No such file or directory
    Generator: execution of make failed. Make command was: /usr/bin/gmake cmTC_94bd2/fast && 
    

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
```

**Comment by fangq** [comment]
I have merged this patch. thanks for contributing!

the Ubuntu 20.04 compilation issue seems to be related to make/cmake instead of cgal. I was able to build everything on an Ubuntu 22.04 box with cgal 5.4. I will troubleshoot the 20.04 error at a later time.

**Comment by lrineau** [comment]
Hi @fangq, there has not been any new version of `iso2mesh` for a long time, and the changes since then is a bit more than cosmetic: https://github.com/fangq/iso2mesh/compare/v1.9.6...master?w=1#files_bucket

I see that you are also maintainer of the Fedora package, that is [FTBFS since CGAL-6.0 was introduced in Rawhide](https://bugzilla.redhat.com/show_bug.cgi?id=2319425) (bug created from [Koschei](https://koschei.fedoraproject.org/package/octave-iso2mesh)).

And `iso2mesh` is also marked for removal from Debian testing [for the same reason (FTBFS)](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1074380): https://tracker.debian.org/pkg/octave-iso2mesh.

Should not you publish a new release to fix those issues?

**Comment by fangq** [comment]
@lrineau, thanks for the message - yes, I agree that creating a new release will be of high priority to include these fixes.

let me work on the documentation update now.

**Pull request merged**
